### ISSUE TITLE
Direct evaluation

### ISSUE THREAD

**Issue by ricklisz** [uni-medical/STU-Net#18]
Dear authors,

I wonder if you could help with clarifying how to conduct direct evaluation using STUNet? I have tried on several MSD datasets but the results were clearly wrong. Did you use the original nnUNetplans from total segmentor dataset? 

Thanks!

**Comment by Ziyan-Huang** [comment]
Dear @ricklisz,

Thank you for reaching out. In order to assist you further, I'd like to gather some more specifics:

1. Which MSD datasets did you test on?
2. Could you describe how you specifically tested STU-Net?
3. When you mention the results were "clearly wrong", could you elaborate a bit more? Are you referring to extremely low metrics or results that are completely off?

Best regards,

Ziyan Huang

**Comment by Ziyan-Huang** [comment]
Additionally, it might be worth checking some details in the data preprocessing steps.

**Comment by ricklisz** [comment]
Thanks for your reply! I figured out the issue. I was able to reproduce results by running nnUNetv2_predict on MSD datasets. On a side note, when you conduct transfer learning, did you use the preprocessed spacings/patch sizes for each dataset or did you use the plan from total segmentor (1.5 spacing and 128 patch size)?

**Comment by Ziyan-Huang** [comment]
Thank you for your inquiry. We use the patch size and spacing generated by nnUNet, not the 1.5 spacing and 128 patch size. The autogenerated values often performed better when train from scratch. In transfer learning, our goal was to improve upon nnUNet's from-scratch results, not just to showcase transfer benefits.
